version: '3'

services:
    # Frontend
    web:
        image: jitsi/web
        ports:
            - '8000:80'
            - '8443:443'
        volumes:
            - ${CONFIG}/meet:/config
        environment:
            - JICOFO_AUTH_USER
            - XMPP_DOMAIN
            - XMPP_AUTH_DOMAIN
            - XMPP_BOSH_URL_BASE
            - XMPP_MUC_DOMAIN
            - TZ
        networks:
            janus.hubl.in:

    # XMPP server
    prosody:
        image: jitsi/prosody
        ports:
            - '5280:5280'
        expose:
            - '5222'
            - '5347'
            - '5280'
        volumes:
            - ${CONFIG}/prosody:/config
        environment:
            - XMPP_DOMAIN
            - XMPP_AUTH_DOMAIN
            - XMPP_MUC_DOMAIN
            - JICOFO_COMPONENT_SECRET
            - JVB_COMPONENT_SECRET
            - JICOFO_AUTH_USER
            - JICOFO_AUTH_PASSWORD
            - TZ
        networks:
            janus.hubl.in:
                aliases:
                    - xmpp.janus.hubl.in

    # Focus component
    jicofo:
        image: jitsi/jicofo
        volumes:
            - ${CONFIG}/jicofo:/config
        environment:
            - XMPP_DOMAIN
            - XMPP_AUTH_DOMAIN
            - XMPP_SERVER=xmpp.janus.hubl.in
            - JICOFO_COMPONENT_SECRET
            - JICOFO_AUTH_USER
            - JICOFO_AUTH_PASSWORD
            - TZ
        networks:
            janus.hubl.in:

    # Video bridge
    jvb:
        image: jitsi/jvb
        ports:
            - "10000:10000/udp"
        volumes:
            - ${CONFIG}/jvb:/config
        environment:
            - DOCKER_HOST_ADDRESS
            - XMPP_DOMAIN
            - XMPP_AUTH_DOMAIN
            - XMPP_SERVER=xmpp.janus.hubl.in
            - JVB_COMPONENT_SECRET
            - JVB_STUN_SERVERS
            - JICOFO_AUTH_USER
            - TZ
        networks:
            janus.hubl.in:

# Custom network so all services can communicate using a FQDN
networks:
    janus.hubl.in:

